name: Publish

on:
  push:
    branches:
      - v4

jobs:
  publish:
    if: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npx quartz build

      - name: Upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: quartz-build
          path: public

      - name: Publish to homelab
        env:
          API_USERNAME: ${{ secrets.HOMELAB_API_USERNAME }}
          API_PASSWORD: ${{ secrets.HOMELAB_API_PASSWORD }}
          ARTIFACT_URL: ${{ github.api_url }}/repos/${{ github.repository }}/actions/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}/zip
        run: |
          curl -X POST \
            -u "$API_USERNAME:$API_PASSWORD" \
            -H "Content-Type: application/json" \
            -d '{"artifactUrl": "$ARTIFACT_URL"}' \
            https://api.adamhl.dev/quartz
