name: Release

on:
  workflow_dispatch: {}

jobs:
  release:
    permissions:
      contents: write
      packages: write
    uses: adamhl8/configs/.github/workflows/release.yml@main
    with:
      docker-image: adamhl.dev
    secrets: inherit

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to watchtower
        env:
          WATCHTOWER_API_TOKEN: ${{ secrets.WATCHTOWER_API_TOKEN }}
        run: |
          curl \
            --fail \
            --request POST \
            --header "Authorization: Bearer $WATCHTOWER_API_TOKEN" \
            https://watchtower.adamhl.dev/v1/update
